# TURPENTINE PLUGIN SETTINGS
#
# When the memory options is enabled, you must have a PC of 32GB or more.

[Fixes]
bSafeExit=true                  	# Fixes crashes related to exiting the game that can be caused erroneously by OBSE64 plugin hooks and also fast quit 
bFFXQueryCrash=true					# Fixes crashes in the ffxQuery function no check Next pointer in struct ffxApiHeader (FSR API)
bWithoutPrefixNL=true				# Removes the [NL] prefix from all strings

[Patches]
bThreads=true						# All threads have priority sets normal, process sets highest, for adequate latency, prohibition on changing processor cores
bMemoryManager=true					# Replaces the global memory manager (+12.5% memory consumption)
bAudioAllocator=true				# Replaces the audio memory allocator (+12.5% memory consumption)
iMaxStdio=2048						# Replaces the maximum stdio handles. Default 512, max 8192 https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170

[Gameplay]
bNoScriptMessageBox=false			# Removes the "MessageBox" function from scripts (without buttons), fixes an issue with annoying messages in gameplay
bNoPoisonConfirmMessage=false		# Removes messages about the use of poison on weapons or bows
bNoTradeSpellConfirmMessage=false	# Removes the message when the spell is purchased
bNoTradeItemConfirmMessage=false	# Removes the message when buying or selling items, but retains the window when selecting a number of items
bNoRechargeItemConfirmMessage=false	# Removes the message when recharging a weapon or all weapons
bNoRepairItemConfirmMessage=false	# Removes the message when all equipment is repaired or one

[Jokes]
bFriendship=false					# Enemies don't attack (they don't see player)